import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const dashboard = readFileSync(new URL("../app/dashboard/DashboardClient.tsx", import.meta.url), "utf8");
const dashboardPage = readFileSync(new URL("../app/dashboard/page.tsx", import.meta.url), "utf8");
const globals = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");
const layout = readFileSync(new URL("../app/layout.tsx", import.meta.url), "utf8");
const landing = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const billingPlan = readFileSync(new URL("../app/BillingPlan.tsx", import.meta.url), "utf8");
const threadsRoute = readFileSync(new URL("../app/api/threads/route.ts", import.meta.url), "utf8");
const sessionSyncRoute = readFileSync(new URL("../app/api/device/sessions/sync/route.ts", import.meta.url), "utf8");
const tasksRoute = readFileSync(new URL("../app/api/tasks/route.ts", import.meta.url), "utf8");
const threadMessagesRoute = readFileSync(new URL("../app/api/thread-messages/route.ts", import.meta.url), "utf8");
const feedbackRoute = readFileSync(new URL("../app/api/feedback/route.ts", import.meta.url), "utf8");
const lessonsRoute = readFileSync(new URL("../app/api/lessons/route.ts", import.meta.url), "utf8");
const lessonsClient = readFileSync(new URL("../app/dashboard/lessons/LessonsClient.tsx", import.meta.url), "utf8");
const schema = readFileSync(new URL("../db/schema.ts", import.meta.url), "utf8");
const taskLeases = readFileSync(new URL("../lib/task-leases.ts", import.meta.url), "utf8");
const threadOperations = readFileSync(new URL("../lib/thread-operations.ts", import.meta.url), "utf8");
const operationClaimRoute = readFileSync(new URL("../app/api/device/thread-operations/claim/route.ts", import.meta.url), "utf8");
const operationCompleteRoute = readFileSync(new URL("../app/api/device/thread-operations/complete/route.ts", import.meta.url), "utf8");
const threadOperationsMigration = readFileSync(new URL("../drizzle/0003_thread_operations.sql", import.meta.url), "utf8");
const webPackage = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const connector = readFileSync(new URL("../../../tools/hermes-cloud-connector.js", import.meta.url), "utf8");
const installer = readFileSync(new URL("../../../saas/install-connector.sh", import.meta.url), "utf8");
