/** Re-export — canonical implementation in hermesNotifications.ts */
export {
  initHermesNotifications,
  initHermesNotifications as initApprovalNotifications,
  requestHermesNotificationPermission,
  requestHermesNotificationPermission as requestApprovalNotificationPermission,
  scheduleApprovalNotification,
  scheduleRunProgressNotification,
  scheduleRunProgressNotification as scheduleStatusNotification,
  scheduleRunCompletedNotification,
  clearRunProgressNotification,
  scheduleRunStallNotification,
  cancelRunStallNotification,
  syncHermesNotificationBadge,
  dismissHermesNotifications,
  dismissHermesNotifications as dismissApprovalNotifications,
  parseApprovalNotificationResponse,
  parseHermesNotificationResponse,
  addApprovalNotificationResponseListener,
  approvalNotificationSubtitle,
  runProgressNotificationTitle,
  type ApprovalNotificationAction,
  type HermesNotificationAction,
  type HermesNotificationTab,
} from './hermesNotifications';
