import type { GatewaySettings, PendingApproval } from '../types/gateway';
import { DEFAULT_GATEWAY_SETTINGS } from '../types/gateway';

export const mockGatewaySettings: GatewaySettings = {
  ...DEFAULT_GATEWAY_SETTINGS,
  gatewayUrl: 'http://192.168.12.208:8642',
  demoMode: false,
  connectionMode: 'gateway',
  thumbgateProActive: true,
};

export const mockPendingApproval: PendingApproval = {
  actionId: 'act_smoke_1',
  toolName: 'run_command',
  reason: 'Dangerous command execution',
  command: 'rm -rf /tmp/hermes-test',
  workspacePath: '/Users/igor/workspace',
  receivedAt: '2026-06-18T12:00:00.000Z',
};

export function mockUseGateway(overrides: Record<string, unknown> = {}) {
  return {
    settings: mockGatewaySettings,
    apiKey: 'sk-test-key',
    thumbgateApiKey: 'sk-thumbgate-test-key',
    mobileToken: '',
    isPaired: false,
    isLoaded: true,
    bootstrapReady: true,
    gatewayBootstrapPhase: 'connected' as const,
    isGatewayReachable: true,
    health: {
      level: 'green' as const,
      status: 'ok',
      gatewayState: 'running',
      checkedAt: '2026-06-18T12:00:00.000Z',
      hostname: 'Igors-MacBook-Pro.local',
      localIp: '192.168.12.208',
    },
    connectionState: 'connected' as const,
    pendingApprovals: [],
    recentReclaims: [],
    presentation: {
      mode: 'visual' as const,
      isDisplayCapable: true,
      visualsOn: true,
      preferAudioFeedback: false,
    },
    sessionGreeting: 'Hermes Mobile connected. Gateway healthy.',
    effectiveGatewayUrl: 'http://192.168.12.208:8642',
    transcriptSyncNonce: 0,
    relayWorkers: [],
    activeRelayWorkerId: null,
    wifiConnected: true,
    refreshHealth: jest.fn().mockResolvedValue(undefined),
    autoConnectGateway: jest.fn().mockResolvedValue('http://192.168.12.208:8642'),
    retryGatewayBootstrap: jest.fn().mockResolvedValue(true),
    applySetupDeepLink: jest.fn().mockResolvedValue(undefined),
    saveSettings: jest.fn().mockResolvedValue(undefined),
    addGatewayProfile: jest.fn().mockResolvedValue(undefined),
    connectEvents: jest.fn(),
    disconnectEvents: jest.fn(),
    completePair: jest.fn().mockResolvedValue(undefined),
    disconnectPair: jest.fn().mockResolvedValue(undefined),
    requestTestIntercept: jest.fn().mockResolvedValue(undefined),
    injectDemoApproval: jest.fn(),
    injectSmokeApproval: jest.fn(),
    enqueueTextApproval: jest.fn(() => true),
    resolveApproval: jest.fn(),
    submitApprovalChoice: jest.fn().mockResolvedValue(undefined),
    sendGateAction: jest.fn().mockResolvedValue(undefined),
    runAgentTool: jest.fn(),
    gatewayProfiles: [
      {
        id: 'mac_192_168_12_208',
        label: 'Mac Pro',
        gatewayUrl: 'http://192.168.12.208:8642',
        hostname: 'Igors-MacBook-Pro',
        localIp: '192.168.12.208',
        addedAt: '2026-06-18T12:00:00.000Z',
      },
    ],
    activeGatewayProfile: {
      id: 'mac_192_168_12_208',
      label: 'Mac Pro',
      gatewayUrl: 'http://192.168.12.208:8642',
      hostname: 'Igors-MacBook-Pro',
      localIp: '192.168.12.208',
      addedAt: '2026-06-18T12:00:00.000Z',
    },
    profileScanning: false,
    profileScanProgress: null,
    profileScanResult: null,
    selectGatewayProfile: jest.fn().mockResolvedValue(undefined),
    removeGatewayProfile: jest.fn().mockResolvedValue(undefined),
    scanForGatewayProfiles: jest.fn().mockResolvedValue([]),
    pendingApprovalEditSeed: null,
    setApprovalEditSeed: jest.fn(),
    clearApprovalEditSeed: jest.fn(),
    pendingChatRelayText: null,
    clearChatRelayText: jest.fn(),
    notificationFocusSessionId: null,
    focusChatSession: jest.fn(),
    clearNotificationFocusSession: jest.fn(),
    runProgress: null,
    setRunProgress: jest.fn(),
    setChatStreamProgressActive: jest.fn(),
    addGatewayListener: jest.fn(),
    removeGatewayListener: jest.fn(),
    wifiConnected: true,
    ...overrides,
  };
}
